version: 2.1

          
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          working_directory: frontend
          command: |
            # Your code here
            npm install
            npm run-script build
      - save_cache:
          paths: [frontend/node_modules]
          key: build-frontend

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          working_directory: backend
          command: |
            # Your code here
             npm install
             npm run-script build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  